
events {}

http {
    error_log /etc/nginx/error_log.log warn;
    client_max_body_size 20m;

    proxy_cache_path /etc/nginx/cache keys_zone=one:500m max_size=1000m;

    server {
        server_name shikimori.local;
        listen 80;
        listen 443 ssl;

        ssl_certificate /etc/letsencrypt/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/privkey.pem;

        # ssl_protocols TLSv1.2 TLSv1.3;
        # ssl_prefer_server_ciphers on;
        # ssl_ciphers EECDH+AESGCM:EDH+AESGCM;

        location / {
            proxy_pass http://web:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Ssl on;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade            $http_upgrade;
            proxy_set_header   Connection         "upgrade";
        }

        location ~ \.(gif|jpg|css|svg|js|png|woff2|webp|ico|jpeg)$ {
            root /var/www/;
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            gzip_static on;
            try_files $uri @proxy;

            types {
                text/css css;
                application/javascript js;
                image/svg+xml svg;
                font/woff2 woff2;
                image/png png;
                image/x-icon ico;
                image/webp webp;
                image/jpeg jpg;
                image/jpeg jpeg;
                image/gif gif;
            }
        }

        location /faye/ {
            proxy_pass http://faye:9292;  # Адрес вашего WebSocket-сервера

            # Обязательные параметры для WebSocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # Дополнительные заголовки
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Увеличиваем таймауты (опционально)
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        location /camo/ {
            proxy_pass http://camo:5566;
        }

        # Редирект HTTP -> HTTPS
        if ($scheme != "https") {
            return 301 https://$host$request_uri;
        }

        location @proxy {
            proxy_pass https://shikimori.one;
            proxy_set_header Cookie "";
            proxy_hide_header Set-Cookie;

            # proxy_set_header Host $host;
        }
    }

    # server {
    #     # listen 80;
    #     listen 443 ssl;
    #     server_name faye.shikimori.local;

    #     ssl_certificate /etc/certificates/shikimori.local+1.pem;
    #     ssl_certificate_key /etc/certificates/shikimori.local+1-key.pem;

    #     location / {
    #         proxy_pass http://faye:9292;  # Адрес вашего WebSocket-сервера

    #         # Обязательные параметры для WebSocket
    #         proxy_http_version 1.1;
    #         proxy_set_header Upgrade $http_upgrade;
    #         proxy_set_header Connection "upgrade";

    #         # Дополнительные заголовки
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    #         # Увеличиваем таймауты (опционально)
    #         proxy_read_timeout 3600s;
    #         proxy_send_timeout 3600s;
    #     }
    # }
}
