:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid

staging:
  :concurrency: 5

production:
  :concurrency: 80

:queues:
  - [high_priority, 8]
  - [critical, 10]
  - [push_notifications, 2]
  - [default, 5]
  - [episode_notifications, 5]
  - [cpu_intensive, 5]
  - [slow_parsers, 5]
  - [torrents_parsers, 5]
  - [mal_parsers, 3]
  - [anime365_parsers, 3]
  - [webm_thumbnails, 5]
  - [history_jobs, 5]
  - [scores_jobs, 4]
  - [low_priority, 1]
  - [cleanup_jobs, 1]
  - [mailers, 5]
  - [imports, 4]
  - [achievements, 6]
  - [chewy, 10]
  - [dangerous_actions, 8]

:limits:
  cpu_intensive: 2
  slow_parsers: 2
  torrents_parsers: 1
  webm_thumbnails: 1
  history_jobs: 1
  scores_jobs: 40
  cleanup_jobs: 1
  # mal_parsers: 40
  mal_parsers: 0
  anime365_parsers: 3
  push_notifications: 5
  imports: 2
  achievements: 50
  episode_notifications: 1
  dangerous_actions: 1
